# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c52a3d2929cd76194d17952a53b58fb38ea33e15f805e9f70b762e1a9359f2d9024d44b740b3409eebf7c24a98a537542ea12df264b6636ccbe39c7baafe43

test:
  secret_key_base: a7e5dc4a9152ab382bf2c6b107889e1d85aa3421d4bb9f1b76801bed23ba49c41bb378c8cd6bb932f51510d658e6c8712f8f66624baecb3bb585d3fc92d78646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
